#!/bin/bash

# GitHub Profile Auto-Update Cronjob Script
# This script provides a backup automation method when GitHub Actions are unreliable

# Configuration
REPO_DIR="/path/to/your/trdat1111"  # Update this path
GITHUB_TOKEN_FILE="$HOME/.github_token"  # Store your token here
LOG_FILE="$REPO_DIR/logs/cronjob.log"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Logging function
log() {
    echo -e "$(date +'%Y-%m-%d %H:%M:%S') [$1] $2" | tee -a "$LOG_FILE"
}

# Error handling
error_exit() {
    log "ERROR" "$1"
    exit 1
}

# Check prerequisites
check_prerequisites() {
    log "INFO" "🔍 Checking prerequisites..."
    
    # Check if repo directory exists
    if [ ! -d "$REPO_DIR" ]; then
        error_exit "Repository directory not found: $REPO_DIR"
    fi
    
    # Check if GitHub token exists
    if [ ! -f "$GITHUB_TOKEN_FILE" ]; then
        error_exit "GitHub token file not found: $GITHUB_TOKEN_FILE"
    fi
    
    # Check if Node.js is available
    if ! command -v node &> /dev/null; then
        error_exit "Node.js not found. Please install Node.js"
    fi
    
    # Check if git is available
    if ! command -v git &> /dev/null; then
        error_exit "Git not found. Please install git"
    fi
    
    # Check if gh CLI is available
    if ! command -v gh &> /dev/null; then
        error_exit "GitHub CLI not found. Please install gh CLI"
    fi
    
    log "INFO" "✅ Prerequisites check passed"
}

# Setup GitHub authentication
setup_github_auth() {
    log "INFO" "🔑 Setting up GitHub authentication..."
    
    export GITHUB_TOKEN=$(cat "$GITHUB_TOKEN_FILE")
    echo "$GITHUB_TOKEN" | gh auth login --with-token
    
    if [ $? -ne 0 ]; then
        error_exit "GitHub authentication failed"
    fi
    
    log "INFO" "✅ GitHub authentication successful"
}

# Check if script should run (rate limiting)
should_run() {
    # Check last successful run from logs
    LAST_SUCCESS=$(grep "SUCCESS.*auto_fetched" "$LOG_FILE" 2>/dev/null | tail -1 | cut -d' ' -f1-2)
    
    if [ -z "$LAST_SUCCESS" ]; then
        log "INFO" "📅 No previous successful run found, proceeding..."
        return 0
    fi
    
    # Calculate hours since last run
    LAST_EPOCH=$(date -d "$LAST_SUCCESS" +%s 2>/dev/null)
    CURRENT_EPOCH=$(date +%s)
    
    if [ -z "$LAST_EPOCH" ]; then
        log "WARN" "⚠️ Could not parse last run time, proceeding..."
        return 0
    fi
    
    HOURS_DIFF=$(( ($CURRENT_EPOCH - $LAST_EPOCH) / 3600 ))
    
    if [ $HOURS_DIFF -ge 4 ]; then
        log "INFO" "⏰ Last run was ${HOURS_DIFF} hours ago, proceeding..."
        return 0
    else
        log "INFO" "⏸️ Last run was only ${HOURS_DIFF} hours ago, skipping to avoid spam"
        return 1
    fi
}

# Fetch articles and update README
update_articles() {
    log "INFO" "🚀 Starting article update process..."
    
    cd "$REPO_DIR" || error_exit "Failed to change to repo directory"
    
    # Pull latest changes
    git pull origin main || error_exit "Failed to pull latest changes"
    
    # Run the automation script
    log "INFO" "📄 Running article fetch script..."
    node add-research.js
    
    if [ $? -ne 0 ]; then
        error_exit "Article fetch script failed"
    fi
    
    # Check if there are changes
    if git diff --quiet README.md; then
        log "INFO" "📝 No changes detected in README.md"
        return 1
    fi
    
    log "INFO" "✨ Changes detected in README.md"
    return 0
}

# Create and merge PR
create_and_merge_pr() {
    log "INFO" "🔀 Creating and merging PR..."
    
    # Configure git
    git config user.name "Automated Cronjob"
    git config user.email "cronjob@automation.local"
    
    # Create unique branch name
    TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
    BRANCH_NAME="cronjob-update-${TIMESTAMP}"
    
    # Create branch and commit
    git checkout -b "$BRANCH_NAME" || error_exit "Failed to create branch"
    git add README.md || error_exit "Failed to add README.md"
    
    COMMIT_MSG="🤖 Cronjob: Auto-update tech articles ($(date +'%Y-%m-%d %H:%M UTC'))"
    git commit -m "$COMMIT_MSG" || error_exit "Failed to commit changes"
    
    # Push branch
    git push origin "$BRANCH_NAME" || error_exit "Failed to push branch"
    
    # Create PR
    PR_TITLE="🤖 Cronjob Tech Articles - $(date +'%Y-%m-%d')"
    PR_BODY="## 🔄 Automated Cronjob Update

Fresh tech articles automatically fetched via cronjob backup system.

### 📊 Update Details:
- **Source**: Cronjob automation  
- **Time**: $(date +'%Y-%m-%d %H:%M:%S UTC')
- **Trigger**: Backup automation system

---
*🤖 Generated by cronjob automation*"
    
    PR_URL=$(gh pr create --base main --head "$BRANCH_NAME" --title "$PR_TITLE" --body "$PR_BODY")
    
    if [ $? -ne 0 ]; then
        error_exit "Failed to create PR"
    fi
    
    log "INFO" "🔗 Created PR: $PR_URL"
    
    # Auto-merge PR
    sleep 5  # Wait a moment for PR to be ready
    PR_NUMBER=$(echo "$PR_URL" | grep -oE '[0-9]+$')
    
    gh pr merge "$PR_NUMBER" --squash --delete-branch --admin
    
    if [ $? -eq 0 ]; then
        log "SUCCESS" "✅ Successfully merged PR #$PR_NUMBER"
        
        # Switch back to main and clean up
        git checkout main
        git pull origin main
        
        return 0
    else
        log "ERROR" "❌ Failed to merge PR #$PR_NUMBER"
        return 1
    fi
}

# Main execution
main() {
    log "INFO" "🚀 Starting cronjob automation..."
    
    # Ensure log directory exists
    mkdir -p "$(dirname "$LOG_FILE")"
    
    # Check prerequisites
    check_prerequisites
    
    # Setup GitHub auth
    setup_github_auth
    
    # Check if should run (rate limiting)
    if ! should_run; then
        log "INFO" "⏭️ Skipping execution due to rate limiting"
        exit 0
    fi
    
    # Update articles
    if update_articles; then
        # Create and merge PR if changes detected
        if create_and_merge_pr; then
            log "SUCCESS" "🎉 Automation completed successfully!"
        else
            error_exit "Failed to create/merge PR"
        fi
    else
        log "INFO" "📝 No changes to commit, automation completed"
    fi
    
    # Clean up old logs
    log "INFO" "🧹 Cleaning up old logs..."
    node automation-logger.js cleanup
}

# Run main function
main "$@"